### ISSUE TITLE
Problem using jRuby 9.1.6.0

### ISSUE THREAD

**Issue by lortega** [Shopify/schmooze#7]
Running tests on jruby-9.1.6.0 I get:
```
➜  schmooze git:(master) ./script/test
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Run options: --seed 35387

# Running:

F.E.EFEEEEFFFFFF

Finished in 0.734000s, 21.7984 runs/s, 14.9864 assertions/s.

  1) Failure:
SchmoozeTest#test_error [/Users/someuser/Workspace/OpenSource/schmooze/test/schmooze_test.rb:95]:
[Schmooze::JavaScript::Error] exception expected, not
Class: <Schmooze::Error>
Message: <"Failed to instantiate Schmooze process:\n[eval]:1\ntry\n^^^\nSyntaxError: Unexpected end of input\n    at Object.exports.runInThisContext (vm.js:78:16)\n    at Object.<anonymous> ([eval]-wrapper:6:22)\n    at Module._compile (module.js:571:32)\n    at Immediate.<anonymous> (bootstrap_node.js:383:29)\n    at runCallback (timers.js:649:20)\n    at tryOnImmediate (timers.js:622:5)\n    at processImmediate [as _immediateCallback] (timers.js:594:5)\nsh: -c: line 1: syntax error near unexpected token `('\nsh: -c: line 1: `  var coffee = require(\"coffee-script\");'\n">
---Backtrace---
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in error'
/Users/someuser/Workspace/OpenSource/schmooze/test/schmooze_test.rb:96:in `block in test_error'
---------------


  2) Error:
SchmoozeTest#test_usage:
Schmooze::Error: Failed to instantiate Schmooze process:
[eval]:1
try
^^^
SyntaxError: Unexpected end of input
    at Object.exports.runInThisContext (vm.js:78:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
sh: -c: line 1: syntax error near unexpected token `('
sh: -c: line 1: `  var coffee = require("coffee-script");'

    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in version'
    /Users/someuser/Workspace/OpenSource/schmooze/test/schmooze_test.rb:91:in `test_usage'


  3) Error:
SchmoozeTest#test_compile_args:
Schmooze::Error: Failed to instantiate Schmooze process:
[eval]:1
try
^^^
SyntaxError: Unexpected end of input
    at Object.exports.runInThisContext (vm.js:78:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
sh: -c: line 1: syntax error near unexpected token `('
sh: -c: line 1: `  var coffee = require("coffee-script");'

    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in compile'
    /Users/someuser/Workspace/OpenSource/schmooze/test/schmooze_test.rb:125:in `test_compile_args'


  4) Failure:
SchmoozeTest#test_async_error [/Users/someuser/Workspace/OpenSource/schmooze/test/schmooze_test.rb:106]:
[Schmooze::JavaScript::Error] exception expected, not
Class: <Schmooze::Error>
Message: <"Failed to instantiate Schmooze process:\n[eval]:1\ntry\n^^^\nSyntaxError: Unexpected end of input\n    at Object.exports.runInThisContext (vm.js:78:16)\n    at Object.<anonymous> ([eval]-wrapper:6:22)\n    at Module._compile (module.js:571:32)\n    at Immediate.<anonymous> (bootstrap_node.js:383:29)\n    at runCallback (timers.js:649:20)\n    at tryOnImmediate (timers.js:622:5)\n    at processImmediate [as _immediateCallback] (timers.js:594:5)\nsh: -c: line 1: syntax error near unexpected token `('\nsh: -c: line 1: `  var coffee = require(\"coffee-script\");'\n">
---Backtrace---
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in async_error'
/Users/someuser/Workspace/OpenSource/schmooze/test/schmooze_test.rb:107:in `block in test_async_error'
---------------


  5) Error:
SchmoozeTest#test_compile:
Schmooze::Error: Failed to instantiate Schmooze process:
[eval]:1
try
^^^
SyntaxError: Unexpected end of input
    at Object.exports.runInThisContext (vm.js:78:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
sh: -c: line 1: syntax error near unexpected token `('
sh: -c: line 1: `  var coffee = require("coffee-script");'

    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in compile'
    /Users/someuser/Workspace/OpenSource/schmooze/test/schmooze_test.rb:113:in `test_compile'


  6) Error:
SchmoozeTest#test_async:
Schmooze::Error: Failed to instantiate Schmooze process:
[eval]:1
try
^^^
SyntaxError: Unexpected end of input
    at Object.exports.runInThisContext (vm.js:78:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
sh: -c: line 1: syntax error near unexpected token `('
sh: -c: line 1: `  var coffee = require("coffee-script");'

    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in async_version'
    /Users/someuser/Workspace/OpenSource/schmooze/test/schmooze_test.rb:102:in `test_async'


  7) Error:
GarbageTest#test_process_is_closed:
Schmooze::Error: Failed to instantiate Schmooze process:
[eval]:1
try
^^^
SyntaxError: Unexpected end of input
    at Object.exports.runInThisContext (vm.js:78:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
sh: -c: line 1: syntax error near unexpected token `}'
sh: -c: line 1: `} catch (e) {'

    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in test'
    /Users/someuser/Workspace/OpenSource/schmooze/test/garbage_test.rb:21:in `block in test_process_is_closed'


  8) Error:
GarbageTest#test_process_is_not_started_until_used:
Schmooze::Error: Failed to instantiate Schmooze process:
[eval]:1
try
^^^
SyntaxError: Unexpected end of input
    at Object.exports.runInThisContext (vm.js:78:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
sh: -c: line 1: syntax error near unexpected token `}'
sh: -c: line 1: `} catch (e) {'

    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
    /Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in test'
    /Users/someuser/Workspace/OpenSource/schmooze/test/garbage_test.rb:11:in `test_process_is_not_started_until_used'


  9) Failure:
ErrorTest#test_import_error [/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:33]:
[Schmooze::DependencyError] exception expected, not
Class: <Schmooze::Error>
Message: <"Failed to instantiate Schmooze process:\n[eval]:1\ntry\n^^^\nSyntaxError: Unexpected end of input\n    at Object.exports.runInThisContext (vm.js:78:16)\n    at Object.<anonymous> ([eval]-wrapper:6:22)\n    at Module._compile (module.js:571:32)\n    at Immediate.<anonymous> (bootstrap_node.js:383:29)\n    at runCallback (timers.js:649:20)\n    at tryOnImmediate (timers.js:622:5)\n    at processImmediate [as _immediateCallback] (timers.js:594:5)\nsh: -c: line 1: syntax error near unexpected token `('\nsh: -c: line 1: `  var nonexistant = require(\"this-package-is-not-here\");'\n">
---Backtrace---
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in bogus'
/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:34:in `block in test_import_error'
---------------


 10) Failure:
ErrorTest#test_late_arriving_dependency [/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:72]:
[Schmooze::DependencyError] exception expected, not
Class: <Schmooze::Error>
Message: <"Failed to instantiate Schmooze process:\n[eval]:1\ntry\n^^^\nSyntaxError: Unexpected end of input\n    at Object.exports.runInThisContext (vm.js:78:16)\n    at Object.<anonymous> ([eval]-wrapper:6:22)\n    at Module._compile (module.js:571:32)\n    at Immediate.<anonymous> (bootstrap_node.js:383:29)\n    at runCallback (timers.js:649:20)\n    at tryOnImmediate (timers.js:622:5)\n    at processImmediate [as _immediateCallback] (timers.js:594:5)\nsh: -c: line 1: syntax error near unexpected token `('\nsh: -c: line 1: `  var empty = require(\"empty\");'\n">
---Backtrace---
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in test'
/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:73:in `block in test_late_arriving_dependency'
---------------


 11) Failure:
ErrorTest#test_unknown_error [/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:89]:
[Schmooze::JavaScript::UnknownError] exception expected, not
Class: <Schmooze::Error>
Message: <"Failed to instantiate Schmooze process:\n[eval]:1\ntry\n^^^\nSyntaxError: Unexpected end of input\n    at Object.exports.runInThisContext (vm.js:78:16)\n    at Object.<anonymous> ([eval]-wrapper:6:22)\n    at Module._compile (module.js:571:32)\n    at Immediate.<anonymous> (bootstrap_node.js:383:29)\n    at runCallback (timers.js:649:20)\n    at tryOnImmediate (timers.js:622:5)\n    at processImmediate [as _immediateCallback] (timers.js:594:5)\nsh: -c: line 1: syntax error near unexpected token `}'\nsh: -c: line 1: `} catch (e) {'\n">
---Backtrace---
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in throw_string'
/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:90:in `block in test_unknown_error'
---------------


 12) Failure:
ErrorTest#test_import_error_but_in_package_json [/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:49]:
[Schmooze::DependencyError] exception expected, not
Class: <Schmooze::Error>
Message: <"Failed to instantiate Schmooze process:\n[eval]:1\ntry\n^^^\nSyntaxError: Unexpected end of input\n    at Object.exports.runInThisContext (vm.js:78:16)\n    at Object.<anonymous> ([eval]-wrapper:6:22)\n    at Module._compile (module.js:571:32)\n    at Immediate.<anonymous> (bootstrap_node.js:383:29)\n    at runCallback (timers.js:649:20)\n    at tryOnImmediate (timers.js:622:5)\n    at processImmediate [as _immediateCallback] (timers.js:594:5)\nsh: -c: line 1: syntax error near unexpected token `('\nsh: -c: line 1: `  var less = require(\"less\");'\n">
---Backtrace---
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in bogus'
/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:50:in `block in test_import_error_but_in_package_json'
---------------


 13) Failure:
ErrorTest#test_import_error_no_package_json [/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:41]:
[Schmooze::DependencyError] exception expected, not
Class: <Schmooze::Error>
Message: <"Failed to instantiate Schmooze process:\n[eval]:1\ntry\n^^^\nSyntaxError: Unexpected end of input\n    at Object.exports.runInThisContext (vm.js:78:16)\n    at Object.<anonymous> ([eval]-wrapper:6:22)\n    at Module._compile (module.js:571:32)\n    at Immediate.<anonymous> (bootstrap_node.js:383:29)\n    at runCallback (timers.js:649:20)\n    at tryOnImmediate (timers.js:622:5)\n    at processImmediate [as _immediateCallback] (timers.js:594:5)\nsh: -c: line 1: syntax error near unexpected token `('\nsh: -c: line 1: `  var nonexistant = require(\"this-package-is-not-here\");'\n">
---Backtrace---
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in bogus'
/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:42:in `block in test_import_error_no_package_json'
---------------


 14) Failure:
ErrorTest#test_javascript_error [/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:57]:
[Schmooze::JavaScript::SyntaxError] exception expected, not
Class: <Schmooze::Error>
Message: <"Failed to instantiate Schmooze process:\n[eval]:1\ntry\n^^^\nSyntaxError: Unexpected end of input\n    at Object.exports.runInThisContext (vm.js:78:16)\n    at Object.<anonymous> ([eval]-wrapper:6:22)\n    at Module._compile (module.js:571:32)\n    at Immediate.<anonymous> (bootstrap_node.js:383:29)\n    at runCallback (timers.js:649:20)\n    at tryOnImmediate (timers.js:622:5)\n    at processImmediate [as _immediateCallback] (timers.js:594:5)\nsh: -c: line 1: syntax error near unexpected token `('\nsh: -c: line 1: `  var coffee = require(\"coffee-script\");'\n">
---Backtrace---
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:74:in `ensure_packages_are_initiated'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:67:in `spawn_process'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:56:in `ensure_process_is_spawned'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:103:in `call_js_method'
/Users/someuser/Workspace/OpenSource/schmooze/lib/schmooze/base.rb:28:in `block in compile'
/Users/someuser/Workspace/OpenSource/schmooze/test/error_test.rb:58:in `block in test_javascript_error'
---------------

16 runs, 11 assertions, 8 failures, 6 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:test:lib" -I"/Users/someuser/.rvm/rubies/jruby-9.1.6.0/lib/ruby/stdlib" "/Users/someuser/.rvm/rubies/jruby-9.1.6.0/lib/ruby/stdlib/rake/rake_test_loader.rb" "test/error_test.rb" "test/garbage_test.rb" "test/schmooze_test.rb" ]
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:1:in `(root)'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `block in start'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/exe/bundle:34:in `<main>'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `<eval>'
/Users/someuser/.rvm/gems/jruby-9.1.6.0@schmooze/bin/jruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by jcode** [comment]
same problem!

**Comment by bouk** [comment]
This seems to be caused by a [jruby bug](https://github.com/jruby/jruby/issues/985). I'll see what I can do

**Comment by jcode** [comment]
Thanks @bouk. We really don't know how to solve this issue. Do you think that is possible to replace the Open3.popen3 implementation for something more simple like:

 `input = system("node -e #{@_schmooze_code}")`

**Comment by bouk** [comment]
I got a start in tackling this, but it turns out there's another incompatibility in that the thread returned from open3 doesn't have the `pid` thread variable, which is needed for the destructor. I'm going to have to spend more time fixing this, it's probably doable by just just `spawn` directly (which is unfortunate)

**Comment by jcode** [comment]
Thanks @bouk, we really appreciate this :)

Is there anything in which we can help?

**Comment by jcode** [comment]
Hi @bouk any update on this? is there a way in which we can help?

Thanks!

**Comment by bouk** [comment]
Sorry for the big delay.

I made a branch: https://github.com/Shopify/schmooze/tree/jruby-support that you can check out to see if it works properly.

**Comment by lortega** [comment]
@bouk I tested your solution in my project and it works properly! 

Thanks!

**Comment by lortega** [comment]
@bouk , are you going to keep both branches or going to merge this one with the master?

**Comment by bouk** [comment]
I'm going to put it into master

**Comment by jcode** [comment]
Thanks @bouk !!!
